import { Customer, Booking, Delivery, Employee, AgencySettings } from '../types';

export const initialAgencySettings: AgencySettings = {
  agencyName: "YTMR-LPG Gas Agency",
  distributorCode: "IND-104829",
  oilCompany: "Indane Gas",
  phone: "+91 98765 43210",
  email: "contact@ytmrlpg.com",
  address: "Plot 42, Industrial Area, Sector 5, City Center",
  refillPrice14kg: 853.50,
  refillPrice19kg: 1785.00,
  refillPrice5kg: 345.00,
  subsidyAmount: 200.00,
  minDaysBetweenRefills: 15,
  smsNotifications: true,
  whatsappNotifications: true,
};

export const initialCustomers: Customer[] = [
  {
    id: "cust-1",
    consumerNo: "IND-804912",
    svNumber: "SV-2021-9941",
    name: "RAJESH KUMAR SHARMA",
    phone: "9812345670",
    email: "rajesh.sharma@gmail.com",
    address: "H.No. 124, Block C, Green Valley Colony",
    careOf: "S/O Ram Lal Sharma",
    scheme: "general",
    cylinderType: "14.2kg",
    oilCompany: "Indane Gas",
    connectionCount: 2,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 14,
    lastRefillDate: "2026-06-10", // 48 days ago (Overdue by 3 days)
    nextEligibleDate: "2026-06-25",
    createdAt: "2023-04-12",
  },
  {
    id: "cust-2",
    consumerNo: "BGT-804913",
    svNumber: "SV-PMUY-4012",
    name: "SUNITA DEVI",
    phone: "9876512340",
    email: "sunita.pmuy@outlook.com",
    address: "Qtr 18, PMUY Enclave, Rampur Village",
    careOf: "W/O Ramesh Kumar",
    scheme: "ujjwala",
    cylinderType: "14.2kg",
    oilCompany: "Bharat Gas",
    connectionCount: 1,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 9,
    lastRefillDate: "2026-06-13", // Exactly 45 days ago (DUE TODAY!)
    nextEligibleDate: "2026-06-28",
    createdAt: "2023-09-20",
  },
  {
    id: "cust-3",
    consumerNo: "IND-804914",
    svNumber: "SV-2022-1102",
    name: "ROYAL KITCHEN RESTAURANT",
    phone: "9988776655",
    email: "manager@royalkitchen.com",
    address: "Shop 12, Main Commercial Hub",
    careOf: "C/O Suresh Gupta (Manager)",
    scheme: "commercial",
    cylinderType: "19kg",
    oilCompany: "Indane Gas",
    connectionCount: 4,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 38,
    lastRefillDate: "2026-05-29", // 60 days ago (Overdue by 15 days)
    nextEligibleDate: "2026-06-13",
    createdAt: "2022-11-05",
  },
  {
    id: "cust-4",
    consumerNo: "BGT-804915",
    svNumber: "SV-PMUY-4055",
    name: "ANITA KUMARI",
    phone: "9123456789",
    address: "Village Post Chandpur, Near Water Tank",
    careOf: "W/O Manoj Kumar",
    scheme: "ujjwala",
    cylinderType: "14.2kg",
    oilCompany: "Bharat Gas",
    connectionCount: 1,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 11,
    lastRefillDate: "2026-07-12", // 16 days ago (Not due)
    nextEligibleDate: "2026-07-27",
    createdAt: "2023-10-11",
  },
  {
    id: "cust-5",
    consumerNo: "IND-804916",
    svNumber: "SV-2020-5590",
    name: "VIKRAM SINGH VERMA",
    phone: "9411223344",
    email: "vsv.verma@yahoo.com",
    address: "Flat 402, Sai Residency, Sector 4",
    careOf: "S/O Mahendra Singh Verma",
    scheme: "general",
    cylinderType: "14.2kg",
    oilCompany: "Indane Gas",
    connectionCount: 2,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 22,
    lastRefillDate: "2026-07-27", // 1 day ago (Not due)
    nextEligibleDate: "2026-08-11",
    createdAt: "2021-02-18",
  },
  {
    id: "cust-6",
    consumerNo: "BGT-804917",
    svNumber: "SV-2024-0012",
    name: "MEENA GUPTA",
    phone: "9355443322",
    address: "House No 89, Shanti Nagar",
    careOf: "W/O Pawan Gupta",
    scheme: "general",
    cylinderType: "5kg",
    oilCompany: "Bharat Gas",
    connectionCount: 1,
    status: "active",
    aadhaarLinked: false,
    bankAccountLinked: true,
    documentUploaded: false,
    totalBookings: 4,
    lastRefillDate: "2026-05-14", // 75 days ago (Overdue by 30 days)
    nextEligibleDate: "2026-05-29",
    createdAt: "2024-01-15",
  },
  {
    id: "cust-7",
    consumerNo: "IND-804918",
    svNumber: "SV-2025-0891",
    name: "SANJAY BISWAS",
    phone: "9830192837",
    address: "Plot 56, Netaji Subhash Road",
    careOf: "S/O Rabindra Biswas",
    scheme: "general",
    cylinderType: "14.2kg",
    oilCompany: "Indane Gas",
    connectionCount: 1,
    status: "active",
    aadhaarLinked: true,
    bankAccountLinked: true,
    documentUploaded: true,
    totalBookings: 8,
    lastRefillDate: "2026-06-13", // Exactly 45 days ago (DUE TODAY!)
    nextEligibleDate: "2026-06-28",
    createdAt: "2025-02-10",
  }
];

export const initialBookings: Booking[] = [
  {
    id: "book-101",
    bookingNo: "LPG-2026-9041",
    customerId: "cust-5",
    consumerNo: "IND-804916",
    customerName: "Vikram Singh Verma",
    phone: "9411223344",
    address: "Flat 402, Sai Residency, Sector 4",
    scheme: "general",
    cylinderType: "14.2kg",
    quantity: 1,
    bookingDate: "2026-07-27",
    status: "pending",
    paymentStatus: "cod",
    amount: 853.50,
  },
  {
    id: "book-102",
    bookingNo: "LPG-2026-9040",
    customerId: "cust-2",
    consumerNo: "IND-804913",
    customerName: "Sunita Devi",
    phone: "9876512340",
    address: "Qtr 18, PMUY Enclave, Rampur Village",
    scheme: "ujjwala",
    cylinderType: "14.2kg",
    quantity: 1,
    bookingDate: "2026-07-26",
    status: "out_for_delivery",
    paymentStatus: "paid",
    amount: 653.50, // Subsidized
    deliveryBoyId: "emp-2",
    deliveryBoyName: "Ramesh Kumar (Rider)",
    cashMemoNo: "CM-2026-7789"
  },
  {
    id: "book-103",
    bookingNo: "LPG-2026-9039",
    customerId: "cust-3",
    consumerNo: "IND-804914",
    customerName: "Royal Kitchen Restaurant",
    phone: "9988776655",
    address: "Shop 12, Main Commercial Hub",
    scheme: "commercial",
    cylinderType: "19kg",
    quantity: 2,
    bookingDate: "2026-07-26",
    status: "delivered",
    paymentStatus: "paid",
    amount: 3570.00,
    deliveryBoyId: "emp-3",
    deliveryBoyName: "Suresh Yadav (Rider)",
    deliveredDate: "2026-07-26",
    cashMemoNo: "CM-2026-7780"
  },
  {
    id: "book-104",
    bookingNo: "LPG-2026-9038",
    customerId: "cust-1",
    consumerNo: "IND-804912",
    customerName: "Rajesh Kumar Sharma",
    phone: "9812345670",
    address: "H.No. 124, Block C, Green Valley Colony",
    scheme: "general",
    cylinderType: "14.2kg",
    quantity: 1,
    bookingDate: "2026-07-25",
    status: "delivered",
    paymentStatus: "paid",
    amount: 853.50,
    deliveryBoyId: "emp-2",
    deliveryBoyName: "Ramesh Kumar (Rider)",
    deliveredDate: "2026-07-25",
    cashMemoNo: "CM-2026-7772"
  }
];

export const initialDeliveries: Delivery[] = [
  {
    id: "del-1",
    bookingId: "book-102",
    bookingNo: "LPG-2026-9040",
    customerName: "Sunita Devi",
    address: "Qtr 18, PMUY Enclave, Rampur Village",
    area: "Rampur Village",
    phone: "9876512340",
    deliveryBoyId: "emp-2",
    deliveryBoyName: "Ramesh Kumar (Rider)",
    status: "out_for_delivery",
    assignedAt: "2026-07-27 08:30 AM",
    notes: "Call consumer before reaching"
  },
  {
    id: "del-2",
    bookingId: "book-103",
    bookingNo: "LPG-2026-9039",
    customerName: "Royal Kitchen Restaurant",
    address: "Shop 12, Main Commercial Hub",
    area: "Main Market",
    phone: "9988776655",
    deliveryBoyId: "emp-3",
    deliveryBoyName: "Suresh Yadav (Rider)",
    status: "delivered",
    assignedAt: "2026-07-26 09:00 AM",
    deliveredAt: "2026-07-26 01:15 PM",
    notes: "Payment received via UPI"
  }
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Amitabh Choudhury",
    email: "admin@ytmrlpg.com",
    phone: "9800011122",
    role: "admin",
    areaAssigned: "Agency Office Head",
    status: "active",
    joinDate: "2020-01-01",
    deliveriesCompleted: 0,
  },
  {
    id: "emp-2",
    name: "Ramesh Kumar",
    email: "ramesh.rider@ytmrlpg.com",
    phone: "9876001122",
    role: "delivery_boy",
    areaAssigned: "Rampur & Green Valley",
    status: "on_duty",
    joinDate: "2022-03-15",
    deliveriesCompleted: 1420,
    vehicleNumber: "UP-16-AZ-4412 (E-Rickshaw)"
  },
  {
    id: "emp-3",
    name: "Suresh Yadav",
    email: "suresh.rider@ytmrlpg.com",
    phone: "9876003344",
    role: "delivery_boy",
    areaAssigned: "Main Market & Sector 4",
    status: "on_duty",
    joinDate: "2021-08-10",
    deliveriesCompleted: 2150,
    vehicleNumber: "UP-16-BZ-9021 (Mini Truck)"
  },
  {
    id: "emp-4",
    name: "Pooja Verma",
    email: "pooja.staff@ytmrlpg.com",
    phone: "9876005566",
    role: "staff",
    areaAssigned: "Front Desk & KYC Verification",
    status: "active",
    joinDate: "2023-01-10",
    deliveriesCompleted: 0
  }
];
